### ISSUE TITLE
Autodiscovery

### ISSUE THREAD

**Issue by mctd** [MadMonkey87/InnerCore.Api.HueSync#1]
> it is likely that there is a discovery mechanism similar to the one of the hue bridge but for now this remains unknown

==> yes of course

Send `{"operation":  null}` in an UDP broadcast message to port 8888 and the box will reply, revealing it's IP (source address of the reply message).

Example on linux:
in a first terminal, setup an UDP server:
`nc -ulv <your_client_IP> 8888`

in a second terminal send the broadcast message:
`echo -n '{"operation":  null}' | socat - udp-datagram:10.255.255.255:8888,broadcast`

Please replace the destination with your subnet's broadcast address.

You should get a reply from the box with a message like :
`Connection from 10.x.x.x 8888 received!
{"operation":1,"name":"HueSyncBox","deviceType":"HSB1","uniqueId":"Cxxxxxxxxxxx"}`

**Comment by MadMonkey87** [comment]
Thx a lot, I'll integrate a discovery service into the library!

**Comment by MadMonkey87** [comment]
The latest release now includes a discovery service
