### ISSUE TITLE
No green led when holding button is it is not working box firmware 1.2.2

### ISSUE THREAD

**Issue by Rep-Hueman** [MadMonkey87/InnerCore.Api.HueSync#2]
Enusre that the box is turned on (led is white) and then press and hold the physical button (~1 sec) on your sync box until the led flashes green.

When the led is white en you hold the button it flashes 1 time green then it turns off led is red.
box firmware 1.2.2

when i klik on enter .....
please press and hold the button on the Hue Sync Box until the led turns green
press enter to continue the registration

Is it disabled now by philips?

**Comment by Rep-Hueman** [comment]
connected to HueSyncBox ApiLevel:3 Led mode:1 Firmware:1.2.2 Build:636568537

**Comment by govabm** [comment]
Hello guys,

How we can Turn on and of off the Box and How we can Switch from HDMI 1 top an Other one 

???

**Comment by Rep-Hueman** [comment]
> I have tested it with the same firmware, that should not be the problem. I assume you already have completed the regular setup using the official app and that the led is constantly white before running the sample application?
> That the led turns red after it flashed green quickly is not a problem, more important is the response you've got from the bridge. How does the sample application behave when the led flashed green quickly?

This is the response i get..

searching for hue sync boxes in the local network
found 1 device(s) -> the first one will be used for this demo
HueSyncBox (192.168.1.20)
connected to HueSyncBox
if you already have an access token you can enter it now or press enter to start the registration progress

please press and hold the button on the Hue Sync Box until the led turns green
press enter to continue the registration

please press and hold the button on the Hue Sync Box until the led turns green
press enter to continue the registration

please press and hold the button on the Hue Sync Box until the led turns green
press enter to continue the registration

**Comment by MadMonkey87** [comment]
Hey @Rep-Hueman 
Sorry for responding so late, I was moving and had no time and no box available to test.
I was able to reproduce your issue and found a problem and a solution:
1) it seems that we have to send a initial register request, then press the button and then send the request again. For that I'll need to change the sample a little, but you can simply press enter first and just go with the next request
2) you have to be rather quick! After you pressed the button on the box, you should quickly press enter in the sample to perform the request

Are you able to register to the box now?

**Comment by Albadalarian** [comment]
Hi there,
I had exactly the same issue. One day my hue sync box was unable to sync to my iOS app. Trying to reconfigure the box, at the page stating “please hold until green flashes and then release” the green appeared for a split second and then red… 
I solve the issue with the phone in fact. I restarted my iPhone, went into the wifi settings, “forget my wifi” and reconnected to my wifi. As simple as that. After that, when I hold the button on the hue box, the green came up and then went back to white instead of red and the app finally completed the setup. 
good luck my friend !
