### ISSUE TITLE
Turn on/off, switch input

### ISSUE THREAD

**Issue by MadMonkey87** [MadMonkey87/InnerCore.Api.HueSync#3]
Hello guys,

How we can Turn on and of off the Box and How we can Switch from HDMI 1 top an Other one 

???

_Originally posted by @govabm in https://github.com/MadMonkey87/InnerCore.Api.HueSync/issues/2#issuecomment-586968460_

**Comment by MadMonkey87** [comment]
Hey @govabm
There is no direct on/off, but instead the box uses the mode:
- PowerSave: the box is in standby = the same what the app considers as off
- any other mode is what the app considers as on

Switching the input is as easy as firing a command. The following snippet creates a command that will do two things at one (powering on the box and switch the input to hdmi 1), but you could also perform these in two separate calls if you wish:

`var command = new ExecutionCommand()
	.SetMode(Mode.Game)
	.SetHdmiSource(HdmiSource.Input1);
await client.PerformExecutionCommandAsync(command);`

Note: you can also get the state and use state.execution.lastmode to see what the last "on" state was and apply this again to "power on" the device.

**Comment by govabm** [comment]
Danke für deine Nachricht ,

Habe aber leider Probleme mit den Token kannst du uns da weiterhelfen ? Zustände kann ich lesen aber sobald ich ein Befehl raus sende bekomme ich eine Info invalid Token 

Von meinem iPhone gesendet

**Comment by govabm** [comment]
Do you have an idea why i get a invalid Token if send a command for Exempel set britness 30%

**Comment by MadMonkey87** [comment]
Can you tell me what steps yo performed exactly? Did you first retrieve a token from the box using the registration procedere?

**Comment by govabm** [comment]
A Friend from symcon Community build a module where u can connect your Box and should Control them But we have some  Problems. we can read the states . If u like i can provide teamviewer 


Von meinem iPhone gesendet

**Comment by govabm** [comment]
thats the first script what we tried to get the State.. it works..

do you see some faults in the script ?


<?php


$APPSECRET = 'MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=';

// $info = GetDeviceInfo();
// var_dump($info);

//$token = Registration();
//var_dump($token);

$data = GetCurrentState();
var_dump($data);



/*
array(3) {
  ["http_code"]=>
  int(200)
  ["header"]=>
  array(5) {
    [0]=>
    string(16) "HTTP/1.1 200 OK
"
    [1]=>
    string(31) "Content-Type: application/json
"
    [2]=>
    string(20) "Content-Length: 253
"
    [3]=>
    string(1) "
"
    [4]=>
    string(0) ""
  }
  ["body"]=>
  string(253) "{"registrationId":"4","accessToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODEwMjQxMDgyMDAsImlzcyI6ImhzYi1DNDI5OTYwMTlBREMiLCJyb2xlIjoidXNlciIsInJpZCI6NCwicmFuIjoiU3ltY29uIiwicmluIjoiU3ltY29uIn0=.KXh8raOc01HuXA3dBdjCOw+qCq9UNzDAI9VKBNIqHSU="}"
}
*/

// string(253) "{"registrationId":"4","accessToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODEwMjQxMDgyMDAsImlzcyI6ImhzYi1DNDI5OTYwMTlBREMiLCJyb2xlIjoidXNlciIsInJpZCI6NCwicmFuIjoiU3ltY29uIiwicmluIjoiU3ltY29uIn0=.KXh8raOc01HuXA3dBdjCOw+qCq9UNzDAI9VKBNIqHSU="}"

function Registration()
    {
        $postfields = ['appName' => 'Symcon', 'appSecret' => 'MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=', 'instanceName' => 'Symcon'];
        return SendCommand('/api/v1/registrations', 'POST', $postfields);
    }

function GetCurrentState()
    {
        $data = SendCommand('/api/v1', 'GET');

        return $data;
    }

/** Device info
     * @return mixed
     */
    function GetDeviceInfo()
    {
        $device_info = SendDevice();

        $name = $device_info->name;
        //$this->WriteAttributeString('name', $name);
        $deviceType = $device_info->deviceType;
        //$this->WriteAttributeString('deviceType', $deviceType);
        $uniqueId = $device_info->uniqueId;
        //$this->WriteAttributeString('uniqueId', $uniqueId);
        $ip = $device_info->ipAddress;
        //$this->WriteAttributeString('ipAddress', $ip);
        $apiLevel = $device_info->apiLevel;
        //$this->WriteAttributeInteger('apiLevel', $apiLevel);
        $firmwareVersion = $device_info->firmwareVersion;
        //$this->WriteAttributeString('firmwareVersion', $firmwareVersion);
        $buildNumber = $device_info->buildNumber;
        //$this->WriteAttributeInteger('buildNumber', $buildNumber);
        $lastCheckedUpdate = $device_info->lastCheckedUpdate;
        //$this->WriteAttributeString('lastCheckedUpdate', $lastCheckedUpdate);

        // $this->WriteAttributeString('updatableBuildNumber', $updatableBuildNumber);
        // $this->WriteAttributeString('updatableFirmwareVersion', $updatableFirmwareVersion);
        // $this->WriteAttributeBoolean('autoUpdateEnabled', $autoUpdateEnabled);
        // $this->WriteAttributeInteger('autoUpdateTime', $autoUpdateTime);
        $ledMode = boolval($device_info->ledMode);
        //$this->WriteAttributeBoolean('ledMode', $ledMode);
        $wifiState = $device_info->wifiState;
        //$this->WriteAttributeString('wifiState', $wifiState);
        // $this->WriteAttributeBoolean('termsAgreed', $termsAgreed);
        return $device_info;
    }


function SendDevice($postfields = null)
    {
        //var_dump($postfields);
        if ($postfields === null) {
            //echo "GET\r\n";
            $data = SendCommand('/api/v1/device', 'GET');
        }
        else
        {
            //echo "PUT\r\n";
            $data = SendCommand('/api/v1/device', 'PUT', $postfields);
        }
        return json_decode($data['body']);
    }

function SendCommand($command, $type, $postfields = null)
    {
        // var_dump($command);
        // var_dump($type);
        // var_dump($postfields);
        $token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODE2MTAyMjcxODMsImlzcyI6ImhzYi1DNDI5OTYwMDcyNTgiLCJyb2xlIjoidXNlciIsInJpZCI6MiwicmFuIjoiU3ltY29uIiwicmluIjoiU3ltY29uIn0=.vHmmPU+k5YToLAonVIK+kpvK7JHNCzNKa2G7bUD7CfY=';
        if ($postfields !== null) {
            $data_json = json_encode($postfields);
        }
        if($command == '/api/v1/device' && $type == 'GET')
        {
            $headers = [];
        }
        elseif($command == '/api/v1/registrations')
        {
            $headers[] = "Accept-Charset: UTF-8";
            $headers[] = "Content-type: application/json;charset=\"UTF-8\"";
        }
        
        elseif($command == '/api/v1' && $type == 'GET')
        {
            $headers[] = "Accept-Charset: UTF-8";
            $headers[] = "Content-type: application/json;charset=\"UTF-8\"";
            $headers[] = "Authorization: Bearer ".$token;
        }
        
        else{
            $headers[] = "Accept-Charset: UTF-8";
            $headers[] = "Content-type: application/json;charset=\"UTF-8\"";
            $headers[] = "Authorization: Bearer ".$token;
        }
        $host = '192.xxx.xxx.xx'; // IP Adresse Sync Box
       //  $url = 'https://'.$this->ReadPropertyString('Host').$command;
         $url = 'https://'.$host.$command;

        $ch = curl_init();
        if($type == 'PUT')
        {
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
            curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json','charset=utf-8', 'Content-Length: ' . strlen($data_json)));
        }
        if($type == 'POST')
        {
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        }
         if($type == 'GET')
        {
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        }
        curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        //curl_setopt($ch, CURLOPT_COOKIEFILE, $this->ReadPropertyString('CookiesFileName')); //this file is read
        // curl_setopt($ch, CURLOPT_COOKIEJAR, $this->ReadPropertyString('CookiesFileName'));  //this file is written
        // curl_setopt($ch, CURLOPT_USERAGENT, $this->ReadPropertyString('browser'));
        curl_setopt($ch, CURLOPT_ENCODING, '');
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLINFO_HEADER_OUT, true);

        
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);

        if ($postfields !== null) {
            curl_setopt($ch, CURLOPT_POSTFIELDS, $data_json);
        }

        curl_setopt($ch, CURLOPT_URL, $url);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            trigger_error('Error:' . curl_error($ch));
        }
        $info = curl_getinfo($ch);
        $header_out = curl_getinfo($ch, CURLINFO_HEADER_OUT);
        var_dump($header_out);
        curl_close($ch);

        return getReturnValues($info, $result);
    }

    function getReturnValues(array $info, string $result): array
    {
        $HeaderSize = $info['header_size'];

        $http_code = $info['http_code'];
        //var_dump($http_code);
        //$this->SendDebug(__FUNCTION__, 'Response (http_code): ' . $http_code, 0);

        $header = explode("\n", substr($result, 0, $HeaderSize));
        //var_dump($header);
        //$this->SendDebug(__FUNCTION__, 'Response (header): ' . json_encode($header), 0);

        $body = substr($result, $HeaderSize);
        //var_dump($body);
        //$this->SendDebug(__FUNCTION__, 'Response (body): ' . $body, 0);

        return ['http_code' => $http_code, 'header' => $header, 'body' => $body];
    }//Start writing your code here

**Comment by govabm** [comment]
sorry now its look better 
`<?php


$APPSECRET = 'MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=';

// $info = GetDeviceInfo();
// var_dump($info);

//$token = Registration();
//var_dump($token);

$data = GetCurrentState();
var_dump($data);



/*
array(3) {
  ["http_code"]=>
  int(200)
  ["header"]=>
  array(5) {
    [0]=>
    string(16) "HTTP/1.1 200 OK
"
    [1]=>
    string(31) "Content-Type: application/json
"
    [2]=>
    string(20) "Content-Length: 253
"
    [3]=>
    string(1) "
"
    [4]=>
    string(0) ""
  }
  ["body"]=>
  string(253) "{"registrationId":"4","accessToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODEwMjQxMDgyMDAsImlzcyI6ImhzYi1DNDI5OTYwMTlBREMiLCJyb2xlIjoidXNlciIsInJpZCI6NCwicmFuIjoiU3ltY29uIiwicmluIjoiU3ltY29uIn0=.KXh8raOc01HuXA3dBdjCOw+qCq9UNzDAI9VKBNIqHSU="}"
}
*/

// string(253) "{"registrationId":"4","accessToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODEwMjQxMDgyMDAsImlzcyI6ImhzYi1DNDI5OTYwMTlBREMiLCJyb2xlIjoidXNlciIsInJpZCI6NCwicmFuIjoiU3ltY29uIiwicmluIjoiU3ltY29uIn0=.KXh8raOc01HuXA3dBdjCOw+qCq9UNzDAI9VKBNIqHSU="}"

function Registration()
    {
        $postfields = ['appName' => 'Symcon', 'appSecret' => 'MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=', 'instanceName' => 'Symcon'];
        return SendCommand('/api/v1/registrations', 'POST', $postfields);
    }

function GetCurrentState()
    {
        $data = SendCommand('/api/v1', 'GET');

        return $data;
    }

/** Device info
     * @return mixed
     */
    function GetDeviceInfo()
    {
        $device_info = SendDevice();

        $name = $device_info->name;
        //$this->WriteAttributeString('name', $name);
        $deviceType = $device_info->deviceType;
        //$this->WriteAttributeString('deviceType', $deviceType);
        $uniqueId = $device_info->uniqueId;
        //$this->WriteAttributeString('uniqueId', $uniqueId);
        $ip = $device_info->ipAddress;
        //$this->WriteAttributeString('ipAddress', $ip);
        $apiLevel = $device_info->apiLevel;
        //$this->WriteAttributeInteger('apiLevel', $apiLevel);
        $firmwareVersion = $device_info->firmwareVersion;
        //$this->WriteAttributeString('firmwareVersion', $firmwareVersion);
        $buildNumber = $device_info->buildNumber;
        //$this->WriteAttributeInteger('buildNumber', $buildNumber);
        $lastCheckedUpdate = $device_info->lastCheckedUpdate;
        //$this->WriteAttributeString('lastCheckedUpdate', $lastCheckedUpdate);

        // $this->WriteAttributeString('updatableBuildNumber', $updatableBuildNumber);
        // $this->WriteAttributeString('updatableFirmwareVersion', $updatableFirmwareVersion);
        // $this->WriteAttributeBoolean('autoUpdateEnabled', $autoUpdateEnabled);
        // $this->WriteAttributeInteger('autoUpdateTime', $autoUpdateTime);
        $ledMode = boolval($device_info->ledMode);
        //$this->WriteAttributeBoolean('ledMode', $ledMode);
        $wifiState = $device_info->wifiState;
        //$this->WriteAttributeString('wifiState', $wifiState);
        // $this->WriteAttributeBoolean('termsAgreed', $termsAgreed);
        return $device_info;
    }


function SendDevice($postfields = null)
    {
        //var_dump($postfields);
        if ($postfields === null) {
            //echo "GET\r\n";
            $data = SendCommand('/api/v1/device', 'GET');
        }
        else
        {
            //echo "PUT\r\n";
            $data = SendCommand('/api/v1/device', 'PUT', $postfields);
        }
        return json_decode($data['body']);
    }

function SendCommand($command, $type, $postfields = null)
    {
        // var_dump($command);
        // var_dump($type);
        // var_dump($postfields);
        $token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODE2MTAyMjcxODMsImlzcyI6ImhzYi1DNDI5OTYwMDcyNTgiLCJyb2xlIjoidXNlciIsInJpZCI6MiwicmFuIjoiU3ltY29uIiwicmluIjoiU3ltY29uIn0=.vHmmPU+k5YToLAonVIK+kpvK7JHNCzNKa2G7bUD7CfY=';
        if ($postfields !== null) {
            $data_json = json_encode($postfields);
        }
        if($command == '/api/v1/device' && $type == 'GET')
        {
            $headers = [];
        }
        elseif($command == '/api/v1/registrations')
        {
            $headers[] = "Accept-Charset: UTF-8";
            $headers[] = "Content-type: application/json;charset=\"UTF-8\"";
        }
        
        elseif($command == '/api/v1' && $type == 'GET')
        {
            $headers[] = "Accept-Charset: UTF-8";
            $headers[] = "Content-type: application/json;charset=\"UTF-8\"";
            $headers[] = "Authorization: Bearer ".$token;
        }
        
        else{
            $headers[] = "Accept-Charset: UTF-8";
            $headers[] = "Content-type: application/json;charset=\"UTF-8\"";
            $headers[] = "Authorization: Bearer ".$token;
        }
        $host = '192.xxx.xxx.xx'; // IP Adresse Sync Box
       //  $url = 'https://'.$this->ReadPropertyString('Host').$command;
         $url = 'https://'.$host.$command;

        $ch = curl_init();
        if($type == 'PUT')
        {
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
            curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json','charset=utf-8', 'Content-Length: ' . strlen($data_json)));
        }
        if($type == 'POST')
        {
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        }
         if($type == 'GET')
        {
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        }
        curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        //curl_setopt($ch, CURLOPT_COOKIEFILE, $this->ReadPropertyString('CookiesFileName')); //this file is read
        // curl_setopt($ch, CURLOPT_COOKIEJAR, $this->ReadPropertyString('CookiesFileName'));  //this file is written
        // curl_setopt($ch, CURLOPT_USERAGENT, $this->ReadPropertyString('browser'));
        curl_setopt($ch, CURLOPT_ENCODING, '');
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLINFO_HEADER_OUT, true);

        
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);

        if ($postfields !== null) {
            curl_setopt($ch, CURLOPT_POSTFIELDS, $data_json);
        }

        curl_setopt($ch, CURLOPT_URL, $url);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            trigger_error('Error:' . curl_error($ch));
        }
        $info = curl_getinfo($ch);
        $header_out = curl_getinfo($ch, CURLINFO_HEADER_OUT);
        var_dump($header_out);
        curl_close($ch);

        return getReturnValues($info, $result);
    }

    function getReturnValues(array $info, string $result): array
    {
        $HeaderSize = $info['header_size'];

        $http_code = $info['http_code'];
        //var_dump($http_code);
        //$this->SendDebug(__FUNCTION__, 'Response (http_code): ' . $http_code, 0);

        $header = explode("\n", substr($result, 0, $HeaderSize));
        //var_dump($header);
        //$this->SendDebug(__FUNCTION__, 'Response (header): ' . json_encode($header), 0);

        $body = substr($result, $HeaderSize);
        //var_dump($body);
        //$this->SendDebug(__FUNCTION__, 'Response (body): ' . $body, 0);

        return ['http_code' => $http_code, 'header' => $header, 'body' => $body];
    }//Start writing your code here`

**Comment by govabm** [comment]
How is the Command for Switch the HDMI 

On php????

The fault with the invalid token are done? 
Mistake in the header....

**Comment by MadMonkey87** [comment]
I can only help you around the api itself and my library I am providing in this repo, I cannot help you with your own php project however.

What you are looking for is the "hdmiSource" field on the execution object, so you can perform a PUT to /api/v1/execution with the following body:
`{
    "hdmiSource": "input1"
}`

**Comment by govabm** [comment]
Thanks it works 

Von meinem iPhone gesendet
